<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net8.0</TargetFrameworks>
		<IsPackable>False</IsPackable>
		<IsTestProject>True</IsTestProject>
		<IsPublishable>False</IsPublishable>
		<GenerateAssemblyInfo>False</GenerateAssemblyInfo>
		<CopyCodeCoverageMetadata>false</CopyCodeCoverageMetadata>
		<NoWarn>CA1416</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\SAL.Flatbed\SAL.Flatbed.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Moq" />
		<PackageReference Include="Moq.AutoMock" />
		<PackageReference Include="FluentAssertions" />
		<PackageReference Include="XUnit" />
		<PackageReference Include="XUnit.Runner.VisualStudio" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" />
		<PackageReference Include="coverlet.collector" />
	</ItemGroup>

</Project>